name: Build AimpYouTubeDL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[16.0,17.0)'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.3'
        architecture: 'x86'
        
    - name: Download Python Embedded
      run: |
        Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-win32.zip" -OutFile "AimpYouTubeDL/python-3.7.3-embed-win32.zip"
      
    - name: Restore NuGet packages
      run: |
        nuget restore AimpYouTubeDL.sln
        
    - name: Build Solution
      run: |
        msbuild AimpYouTubeDL.sln /p:Configuration=Release /p:Platform=x86
        
    - name: Create Release Artifact
      run: |
        $pluginPath = "C:\Program Files (x86)\AIMP\Plugins\aimp_youtubedl"
        if (Test-Path $pluginPath) {
          Compress-Archive -Path "$pluginPath\*" -DestinationPath "aimp_youtubedl.zip" -Force
        }
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aimp_youtubedl
        path: aimp_youtubedl.zip
