name: Build AimpYouTubeDL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Visual Studio Components
      uses: microsoft/setup-msbuild@v1.3.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
        
    - name: Restore NuGet packages
      run: nuget restore AimpYouTubeDL.sln
        
    - name: Build C++ Project
      run: msbuild AimpSharpRef/AimpSharpRef.vcxproj /p:Configuration=Release /p:Platform=Win32
        
    - name: Build C# Project
      run: msbuild AimpYouTubeDL/AimpYouTubeDL.csproj /p:Configuration=Release /p:Platform=x86

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AimpYouTubeDL
        path: |
          AimpSharpRef/Release/*.dll
          AimpYouTubeDL/bin/Release/*.dll
