name: Build and Test AimpYouTubeDL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Для работы с .NET на Windows

    steps:
      # Шаг 1: Checkout кода из репозитория
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установить .NET SDK
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'  # Установите версию .NET, которая используется в проекте

      # Шаг 3: Восстановление зависимостей
      - name: Restore dependencies
        run: dotnet restore

      # Шаг 4: Сборка проекта
      - name: Build the project
        run: dotnet build --configuration Release

      # Шаг 5: Запуск юнит-тестов (если они есть)
      - name: Run tests
        run: dotnet test --configuration Release

      # Шаг 6: (Опционально) Публикация артефактов сборки
      - name: Publish build artifacts
        run: |
          mkdir -p output
          dotnet publish --configuration Release --output ./output

      # Шаг 7: (Опционально) Прочие действия, например, загрузка артефактов или деплой
      # можно добавить дополнительные шаги в зависимости от требований проекта
