name: Build AimpYouTubeDL

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: AimpYouTubeDL.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x86]
# platform: [x86, x64]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Visual Studio Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.platform }}

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AimpYouTubeDL-${{matrix.platform}}
	path: build/Release/
   #     path: |
   #       ${{matrix.platform}}\${{env.BUILD_CONFIGURATION}}\*.dll
   #       ${{matrix.platform}}\${{env.BUILD_CONFIGURATION}}\*.pdb
   
